api = "0.4"

[buildpack]
id = "heroku/java"
version = "0.1.0"
name = "Java"

  [publish.Ignore]
  files = [
    "etc/",
    "spec/",
    "test/",
    "vendor/",
    ".gitignore",
    ".github/",
    ".travis.yml",
    "circle.yml",
    "hatchet.json",
    "Gemfile",
    "Gemfile.lock"
  ]

# this is to allow testing of other stack compatibility and is not a guarantee
[[stacks]]
id = "heroku-16"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

# this is to allow testing of other stack compatibility and is not a guarantee
[[stacks]]
id = "io.buildpacks.stacks.bionic"
